// AUTO-GENERATED FILE, HAND-FILLED.
// Stub generated by `bal openapi --mode service` from
// specs/design/components/todo-api/openapi.yaml; every resource body below
// was filled in by hand. The types below (TodoItem, TodoItemCreate, ...)
// are the generator's own — unchanged.

import ballerina/http;
import ballerina/time;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todo items
    #
    # + return - returns can be any of following types
    # inline_response_200 (A page of the caller's todo items)
    # http:Unauthorized (Missing or invalid sign-in)
    resource function get me/todo\-items(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorizedError();
        }
        GatewayCaller caller = callerResult;

        int pageLimit = normalizeLimit('limit);
        int pageOffset = offset < 0 ? 0 : offset;

        int totalCount = check countTodoItems(caller.userId);
        TodoItemRow[] rows = check listTodoItemRows(caller.userId, pageLimit, pageOffset);
        TodoItem[] items = from TodoItemRow row in rows select rowToTodoItem(row);

        string? next = (pageOffset + pageLimit < totalCount)
            ? string `/me/todo-items?limit=${pageLimit}&offset=${pageOffset + pageLimit}`
            : ();
        string? previous = (pageOffset > 0)
            ? string `/me/todo-items?limit=${pageLimit}&offset=${previousOffset(pageOffset, pageLimit)}`
            : ();

        return {
            count: totalCount,
            next,
            previous,
            data: items
        };
    }

    # Create a new todo item for the caller
    #
    # + return - returns can be any of following types
    # TodoItem (The created todo item)
    # ErrorBadRequest (The title is missing or invalid)
    # ErrorUnauthorized (Missing or invalid sign-in)
    resource function post me/todo\-items(http:RequestContext ctx, @http:Payload TodoItemCreate payload)
            returns TodoItem|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorizedError();
        }
        GatewayCaller caller = callerResult;

        string title = payload.title.trim();
        if title == "" {
            return badRequestError("title is required");
        }

        TodoItemRow row = check createTodoItemRow(caller.userId, title);
        return rowToTodoItem(row);
    }

    # A single todo item of the caller's
    #
    # + return - returns can be any of following types
    # TodoItem (The todo item)
    # ErrorUnauthorized (Missing or invalid sign-in)
    # ErrorNotFound (No such todo item of the caller's)
    resource function get me/todo\-items/[string todoItemId](http:RequestContext ctx)
            returns TodoItem|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorizedError();
        }
        GatewayCaller caller = callerResult;

        TodoItemRow? row = check getTodoItemRow(caller.userId, todoItemId);
        if row is () {
            return notFoundError();
        }
        return rowToTodoItem(row);
    }

    # Edit or complete a todo item of the caller's
    #
    # + return - returns can be any of following types
    # TodoItem (The updated todo item)
    # ErrorBadRequest (The update is invalid)
    # ErrorUnauthorized (Missing or invalid sign-in)
    # ErrorNotFound (No such todo item of the caller's)
    resource function patch me/todo\-items/[string todoItemId](http:RequestContext ctx,
            @http:Payload TodoItemUpdate payload)
            returns TodoItem|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorizedError();
        }
        GatewayCaller caller = callerResult;

        string? newTitle = ();
        string? payloadTitle = payload?.title;
        if payloadTitle is string {
            newTitle = payloadTitle.trim();
            if newTitle == "" {
                return badRequestError("title must not be blank");
            }
        }
        boolean? newCompleted = payload?.completed;

        TodoItemRow? row = check updateTodoItemRow(caller.userId, todoItemId, newTitle, newCompleted);
        if row is () {
            return notFoundError();
        }
        return rowToTodoItem(row);
    }

    # Delete a todo item of the caller's
    #
    # + return - returns can be any of following types
    # http:NoContent (The todo item was deleted)
    # ErrorUnauthorized (Missing or invalid sign-in)
    # ErrorNotFound (No such todo item of the caller's)
    resource function delete me/todo\-items/[string todoItemId](http:RequestContext ctx)
            returns http:NoContent|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorizedError();
        }
        GatewayCaller caller = callerResult;

        boolean deleted = check deleteTodoItemRow(caller.userId, todoItemId);
        if !deleted {
            return notFoundError();
        }
        return http:NO_CONTENT;
    }
}

# Clamps the caller's requested page size to the contract's bounds (1..100),
# falling back to the default of 20 for a non-positive value.
#
# + requested - the caller's `limit` query parameter
# + return - the page size to use
function normalizeLimit(int requested) returns int {
    if requested < 1 {
        return 20;
    }
    if requested > 100 {
        return 100;
    }
    return requested;
}

# The previous page's offset, never negative.
#
# + pageOffset - the current page's offset
# + pageLimit - the current page's size
# + return - the offset to use for the previous page
function previousOffset(int pageOffset, int pageLimit) returns int {
    int prev = pageOffset - pageLimit;
    return prev < 0 ? 0 : prev;
}

# Converts a stored row into the contract's wire shape.
#
# + row - the stored row
# + return - the item as the contract spells it
function rowToTodoItem(TodoItemRow row) returns TodoItem {
    return {
        id: row.id,
        title: row.title,
        completed: row.completed,
        createdAt: time:utcToString(row.createdAt),
        updatedAt: time:utcToString(row.updatedAt)
    };
}

function unauthorizedError() returns ErrorUnauthorized {
    return {body: {code: 401, message: "missing or invalid sign-in"}};
}

function notFoundError() returns ErrorNotFound {
    return {body: {code: 404, message: "no such todo item of the caller's"}};
}

function badRequestError(string message) returns ErrorBadRequest {
    return {body: {code: 400, message}};
}

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoItem record {
    string id;
    string title;
    boolean completed;
    string createdAt;
    string updatedAt;
};

public type TodoItemCreate record {
    string title;
};

public type TodoItemUpdate record {
    string title?;
    boolean completed?;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    TodoItem[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
